### ISSUE TITLE
ERROR in Error: Unexpected value 'CeiboShare in /home/imhta/angular-projects/talentedbeings/node_modules/ng2-social-share/src/ng2-social-share.d.ts' 

### ISSUE THREAD

**Issue by nijeeshjoshy** [Epotignano/ng2-social-share#13]
```
> ERROR in Error: Unexpected value 'CeiboShare in /home/imhta/angular-projects/talentedbeings/node_modules/ng2-social-share/src/ng2-social-share.d.ts' imported by the module 'AppModule in /home/imhta/angular-projects/talentedbeings/src/app/app.module.ts'. Please add a @NgModule annotation.
>     at syntaxError (/home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler/bundles/compiler.umd.js:1725:34)
>     at /home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler/bundles/compiler.umd.js:15417:44
>     at Array.forEach (<anonymous>)
>     at CompileMetadataResolver.getNgModuleMetadata (/home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler/bundles/compiler.umd.js:15400:49)
>     at addNgModule (/home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:58)
>     at /home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler/bundles/compiler.umd.js:24252:14
>     at Array.forEach (<anonymous>)
>     at _createNgModules (/home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler/bundles/compiler.umd.js:24251:26)
>     at analyzeNgModules (/home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler/bundles/compiler.umd.js:24126:14)
>     at analyzeAndValidateNgModules (/home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler/bundles/compiler.umd.js:24136:35)
>     at AotCompiler.analyzeModulesAsync (/home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler/bundles/compiler.umd.js:23772:46)
>     at CodeGenerator.codegen (/home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
>     at Function.NgTools_InternalApi_NG_2.codeGen (/home/imhta/angular-projects/talentedbeings/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
>     at _donePromise.Promise.resolve.then (/home/imhta/angular-projects/talentedbeings/node_modules/@ngtools/webpack/src/plugin.js:386:44)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
```

Iam getting this error after runing a build

my live live development server was running without any problem but now not even live development server is working

## this is my app module 
```

import { PostContainerService } from './post-container/post-container/post-container.service';
import { NominatorsService } from './nominators/nominators.service';
import { SingleNominineeServerConnectionService } from './single-nominee-registration/single-nomininee-server-connection/single-nomininee-server-connection.service';
import { AddNominatorServiceService } from './add-nominator/add-nominator-service/add-nominator-service.service';
import { ManagePostService } from './manage-post/manage-post/manage-post.service';
import { OtpverifyService } from './otp-popup-field/otpverify/otpverify.service';
import { MyNomineeService } from './my-nominee/my-nominee.service';
import { PostService } from './post/post.service';

import { Google0AuthService } from './google0-auth/google0-auth.service';
import { HttpRequestsService } from './http-requests/http-requests.service';
import { AuthService } from './login/auth/auth.service';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, CUSTOM_ELEMENTS_SCHEMA, Component, NO_ERRORS_SCHEMA } from '@angular/core';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import { HttpModule,XHRBackend, RequestOptions } from '@angular/http';
import { ServerURLInterceptor } from './intercepter/interceptor';
import { InterceptorService } from 'ng2-interceptors';

import { CommonModule }       from '@angular/common';
import { FormsModule,ReactiveFormsModule  } from "@angular/forms";
import { AppComponent, SideBar } from './app.component';
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';
import { DragScrollModule } from 'angular2-drag-scroll';
import {MdCheckboxModule,
        MdCardModule,
        MdButtonModule,
        MdInputModule,
        MdTabsModule,
        MdSelectModule,
        MdIconModule,
        MdProgressBarModule,
        MatProgressSpinnerModule,
        MdSidenavModule,
        MdToolbarModule,
        MdExpansionModule,
        MdButtonToggleModule,
        MdChipsModule,
        MdMenuModule,
        MdSliderModule,
        MdTooltipModule,
        MdListModule,
        MdGridListModule,
        MatStepperModule,
        MdDatepickerModule,
        MdRadioModule,
        MdNativeDateModule,
        MdDialogModule,
        MatMenuModule,
        MatTableModule,
        MatAutocompleteModule

} from '@angular/material';
import { LoginComponent } from './login/login.component';
import { SiLoginComponent } from './login/si-login/si-login.component';
import { SuLoginComponent } from './login/su-login/su-login.component';
import { LsLogoComponent } from './ls-logo/ls-logo.component';
import { LLogoComponent } from './l-logo/l-logo.component';
import { SLogoComponent } from './s-logo/s-logo.component';
import { WallComponent } from './wall/wall.component';

import { FabMoreComponent } from './fab-more/fab-more.component';

import { AddAdComponent } from './add-ad/add-ad.component';

import { PostComponent } from './post/post.component';
import { NotfoundComponent } from './notfound/notfound.component';
import { RouterModule} from '@angular/router';
import { Social0authComponent } from './social0auth/social0auth.component';
import { ForgotPassComponent } from './forgot-pass/forgot-pass.component';
import { OtpVerificationComponent } from './otp-verification/otp-verification.component';
import { NewPassComponent } from './new-pass/new-pass.component';
import { MessageComponent } from './message/message.component';
import { NavComponent } from './nav/nav.component';
import { GeneralProfileComponent } from './general-profile/general-profile.component';
import { MyprofileEditComponent } from './myprofile-edit/myprofile-edit.component';
import { UploadComponent } from './upload/upload.component';
import { AchivementsComponent } from './achivements/achivements.component';
import { ManagePostComponent } from './manage-post/manage-post.component';
import { ScanComponent } from './scan/scan.component';
import { MyNomineesComponent } from './my-nominees/my-nominees.component';
import { LikeComponent } from './like/like.component';
import { ProfileComponent } from './profile/profile.component';
import { ActivityComponent } from './activity/activity.component';
import { MomentModule } from 'angular2-moment';

import { PostPageComponent } from './post-page/post-page.component';
import { CreateEventComponent } from './create-event/create-event.component';
import { ShareDialogComponent } from './share-dialog/share-dialog.component';
import { CeiboShare } from 'ng2-social-share';
import { AdminConsoleComponent } from './admin-console/admin-console.component';
import { OrgRegistrationComponent } from './org-registration/org-registration.component';
import { SingleNomineeRegistrationComponent } from './single-nominee-registration/single-nominee-registration.component';
import { BulkNomineeRegistrationComponent } from './bulk-nominee-registration/bulk-nominee-registration.component';
import { TestComponent } from './test/test.component';
import { NgUploaderModule } from 'ngx-uploader';
import { ReportComponent } from './report/report.component';
import { OtpPopupFieldComponent } from './otp-popup-field/otp-popup-field.component';
import { NominatorsComponent } from './nominators/nominators.component';
import { ConfirmComponent } from './manage-post/confirm/confirm.component';
import { AddNomineeComponent } from './add-nominee/add-nominee.component';
import { AddNominatorComponent } from './add-nominator/add-nominator.component';
import { AddNomineeService } from './add-nominee/add-nominee/add-nominee.service';
import { ToolbarComponent } from './toolbar/toolbar.component';
import { AfterLogToolbarComponent } from './after-log-toolbar/after-log-toolbar.component';
import { FooterComponent } from './footer/footer.component';
import { CreateDialogComponent } from './create-dialog/create-dialog.component';
import { AddDialogComponent } from './add-dialog/add-dialog.component';
import { OrgRegServerConectionService } from './org-registration/org-reg-server-conection/org-reg-server-conection.service';
import { CommentComponent } from './comment/comment.component';
import { PostContainerComponent } from './post-container/post-container.component';
import { UploadServiceService } from './upload/upload-service/upload-service.service';
import { NomineeAddComponent } from './nominee-add/nominee-add.component';


export function interceptorFactory(xhrBackend: XHRBackend, requestOptions: RequestOptions, serverURLInterceptor:ServerURLInterceptor)
{ // Add it here
  let service = new InterceptorService(xhrBackend, requestOptions);
  service.addInterceptor(serverURLInterceptor); // Add it here
  return service;
}


@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    SiLoginComponent,
    SuLoginComponent,
    LsLogoComponent,
    LLogoComponent,
    SLogoComponent,
    WallComponent,
    FabMoreComponent,
    AddAdComponent,
    PostComponent,
    NotfoundComponent,
    Social0authComponent,
    ForgotPassComponent,
    OtpVerificationComponent,
    NewPassComponent,
    MessageComponent,
    NavComponent,
    CeiboShare,
    GeneralProfileComponent,
    MyprofileEditComponent,
    UploadComponent,
    AchivementsComponent,
    ManagePostComponent,
    ScanComponent,
    MyNomineesComponent,
    LikeComponent,
    ProfileComponent,
    ActivityComponent,
    PostPageComponent,
    CreateEventComponent,
    ShareDialogComponent,
    AdminConsoleComponent,
    OrgRegistrationComponent,
    SingleNomineeRegistrationComponent,
    BulkNomineeRegistrationComponent,
    TestComponent,
    ReportComponent,
    OtpPopupFieldComponent,
    NominatorsComponent,
    ConfirmComponent,
    AddNomineeComponent,
    AddNominatorComponent,
    ToolbarComponent,
    AfterLogToolbarComponent,
    FooterComponent,
    CreateDialogComponent,
    AddDialogComponent,
    CommentComponent,
    PostContainerComponent,
    NomineeAddComponent,
    
   

  ],
  imports: [
    
    MomentModule,
    BrowserModule,
    BrowserAnimationsModule,
    MdCheckboxModule,
    MdCardModule,
    MdButtonModule,
    MdInputModule,
    MdTabsModule,
    ReactiveFormsModule,
    FormsModule,
    HttpModule,
    MdSelectModule,
    MdIconModule,
    MdProgressBarModule,
    MdSidenavModule,
    MdToolbarModule,
    MdExpansionModule,
    MdButtonToggleModule,
    MdChipsModule,
    MdMenuModule,
    MdSliderModule,
    MdTooltipModule,
    MdListModule,
    MdGridListModule,
    MatStepperModule,
    MdDatepickerModule,
    MdRadioModule,
    DragScrollModule,
    MdNativeDateModule ,
    MdDialogModule,
    NgUploaderModule,
    BrowserModule,
    MatMenuModule,
    MatTableModule,
    MatAutocompleteModule,
    NgbModule,
 
    NgbModule.forRoot(),
    
    RouterModule.forRoot([
  
      {
        path:'',
        component:WallComponent
      },
      {
        path:'wall',
        component:WallComponent,
        children:[
          {
            path:'share',
            component:ShareDialogComponent
          },
       
        ]
      },
      {
        path:'my/nominees',
        component:MyNomineesComponent,
      },
      {
        path:'my/nominators',
        component:NominatorsComponent
      },
      {
        path:'add/nominator',
        component:AddNominatorComponent
      },
      {
        path:'add/nominee',
        component:AddNomineeComponent
      },
      {
        path:'add/org',
        component:OrgRegistrationComponent
      },
      {
        path:'profile/:id',
        component:ProfileComponent

      },

      {
        path:'post/upload',
        component:UploadComponent
      },
      {
        path:'popup/add/nominee',
        component:NomineeAddComponent
      },
      {
        path:'post/:id',
        component:PostPageComponent
      },
      {
        path:'post/manage',
        component:ManagePostComponent,
        children:[{
          path:'confirm',
          component:ConfirmComponent
          
        }]
      },
      {
        path:'events/create',
        component:CreateEventComponent
      },
      {
        path:'create',
        component:CreateDialogComponent
      },
      {
        path:'add',
        component:AddDialogComponent
      },
      {
        path:'report',
        component:ReportComponent

      },
      {
        path:'',
        component:NavComponent,
        outlet:'topNav'

      },
      {
        path:'after',
        component:AfterLogToolbarComponent,
        outlet:'toolbar'
      },
      {
        path:'sign/in',
        component:LoginComponent,
      },
      {
        path:'sign/up',
        component:SuLoginComponent,
      },
      {
        path:'',
        component:FooterComponent,
        outlet:'bottom'

      },
      {
        path:'',
        component:AddAdComponent,
        outlet:'leftSide'

      },
      {
        path:'',
        component:ToolbarComponent,
        outlet:'toolbar'

      },
     
      {
        path:'**',
         component:NotfoundComponent
      } ,
     

    ])
  ],
  exports: [
    RouterModule
  ],
  providers: [AuthService,
              HttpRequestsService,
              Google0AuthService,
              ServerURLInterceptor,
              PostService,
              SideBar,
              MyNomineeService,
              NominatorsService,
              OtpverifyService,
              ManagePostService,
              AddNomineeService,
              AddNominatorServiceService,
              SingleNominineeServerConnectionService,
              OrgRegServerConectionService,
              PostContainerService,
              UploadServiceService,
              
              {
                provide: InterceptorService,
                useFactory: interceptorFactory,
                deps: [XHRBackend, RequestOptions, ServerURLInterceptor] }
                
  ],
  bootstrap: [AppComponent],
  schemas: [ CUSTOM_ELEMENTS_SCHEMA,NO_ERRORS_SCHEMA ]
})
export class AppModule { }

export declare class FacebookParams {
  u: string;
}
export class GooglePlusParams {
  url: string
}
export class LinkedinParams {
  url:string
}
export class TwitterParams {
  text: string;
  url: string;
  hashtags: string;
  via: string;
}
export declare class PinterestParams {
  url: string;
  media: string;
  description: string;
}


```

**Comment by snazami** [comment]
I have the exact same issues. Any progress on this?

**Comment by nijeeshjoshy** [comment]
Dont know i have to comment it out just in-order to get the build work.
Done my project without it

**Comment by bergergit** [comment]
I have the same issue. Trying to compile using AOT (--prod). Don't know how to fix it
